spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=YOUR_DB_NAME;encrypt=true;trustServerCertificate=true
spring.datasource.username=cp_user
spring.datasource.password=ChangeThis#123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver