server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CreativePulseDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YOUR_PASSWORD_HERE
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.sql.init.mode=never
spring.jackson.serialization.write-dates-as-timestamps=false
