<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html><head><title>Campaign Management</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/app.css"></head>
<body><div class="layout"><aside class="sidebar"><div class="brand">Creative<span>Pulse</span></div><div class="role">CAMPAIGN MANAGER</div><a href="${pageContext.request.contextPath}/campaign-manager">Overview</a><a class="active" href="#">Campaign Management</a><a href="${pageContext.request.contextPath}/campaign-manager/tasks">Employee Task Management</a><a href="${pageContext.request.contextPath}/clients">Client Management</a><div class="separator"></div><a href="#">Advertisement Management</a><a href="#">Billing & Payment</a><a href="#">Report Management</a></aside>
<main class="content"><header><div><span class="eyebrow">CAMPAIGN MANAGEMENT</span><h1>Campaigns</h1><p>Create, monitor, update and remove advertising campaigns.</p></div><a class="btn" href="${pageContext.request.contextPath}/campaign-manager/campaigns/new">+ Add Campaign</a></header>
<div class="mini-cards"><div>Total <b>${total}</b></div><div>Active <b>${active}</b></div><div>Completed <b>${completed}</b></div></div>
<div class="table-card"><table><thead><tr><th>Campaign</th><th>Client</th><th>Schedule</th><th>Status</th><th>Progress</th><th>Manager</th><th>Actions</th></tr></thead><tbody>
<c:forEach var="c" items="${campaigns}"><tr><td><b>${c.name}</b><br><small>${c.description}</small></td><td>${c.clientName}</td><td>${c.startDate} → ${c.endDate}</td><td><span class="badge">${c.status}</span></td><td><div class="progress"><i style="width:${c.progress}%"></i></div>${c.progress}%</td><td>${c.managerName}</td><td class="actions"><a href="${pageContext.request.contextPath}/campaign-manager/campaigns/edit/${c.id}">Edit</a><a href="${pageContext.request.contextPath}/campaign-manager/campaigns/delete/${c.id}" onclick="return confirm('Delete this campaign?')">Delete</a></td></tr></c:forEach>
</tbody></table></div></main></div></body></html>
